# Generated by Django 3.1.5 on 2021-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('output', models.TextField()),
                ('script', models.TextField()),
                ('execute_script', models.BooleanField(default=False)),
            ],
        ),
    ]
