# Generated by Django 3.1.5 on 2021-01-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='integration',
            new_name='Interaction',
        ),
    ]
