# Generated by Django 3.1.5 on 2021-01-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20210113_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
