# Generated by Django 3.1.5 on 2021-01-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_auto_20210113_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='input',
            new_name='input_value',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='execute_script',
        ),
        migrations.AddField(
            model_name='interaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='script',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
